# Serializating ML Models

In [ ]:
- serialize ml models
    - json
    - pickle
    - joblib

- resume training from checkpoint

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('CarPrice_Assignment.csv')
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [3]:
df.shape

(205, 26)

In [4]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
df.drop(['car_ID', 'symboling', 'CarName'], axis=1, inplace=True)

In [6]:
df = pd.get_dummies(df)

df.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
0       88.6      168.8      64.1       48.8        2548         130   
1       88.6      168.8      64.1       48.8        2548         130   
2       94.5      171.2      65.5       52.4        2823         152   
3       99.8      176.6      66.2       54.3        2337         109   
4       99.4      176.6      66.4       54.3        2824         136   

   boreratio  stroke  compressionratio  horsepower  ...  \
0       3.47    2.68               9.0         111  ...   
1       3.47    2.68               9.0         111  ...   
2       2.68    3.47               9.0         154  ...   
3       3.19    3.40              10.0         102  ...   
4       3.19    3.40               8.0         115  ...   

   cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
0                      0                   0                0   
1                      0                   0                0   
2                      0                   0                0   
3                      0                   0                0   
4                      0                   0                0   

   fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
0                0                0               0               0   
1                0                0               0               0   
2                0                0               0               0   
3                0                0               0               0   
4                0                0               0               0   

   fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
0                1                0                0  
1                1                0                0  
2                1                0                0  
3                1                0                0  
4                1                0                0  

[5 rows x 52 columns]

In [7]:
df.shape

(205, 52)

In [ ]:
# gender
# male
# female
# male
# other

# male  female  other
#  1     0       0
#  0     1       0
#  1     0       0
#  0     0       1

In [8]:
x = df.drop('price', axis=1)

y = df['price']

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2)

In [11]:
model = LinearRegression()

model.fit(xtrain, ytrain)

LinearRegression()

In [12]:
model.score(xtrain, ytrain)

0.9544875508395988

In [13]:
ypred = model.predict(xtest)

ypred

array([18619.15757811,  7662.62678786, 20822.50838869, 27539.25567201,
       17495.08927843, 11178.52046327,  6409.85832609, 14208.14141144,
       18674.54249815, 38283.29871344,  9005.03478484,  6949.49106947,
        7853.57661209, 16988.31650221,  9924.86067702,  9147.01488267,
        7246.29671961, 30082.33172101,  7854.61605152,  6273.90636822,
        5706.27220937, 21211.7248001 , 15423.67305019, 22017.09222772,
        9256.81830812,  8404.68250386,  7631.28471913,  8579.88251782,
        6409.85832609, 18782.0811832 ,  8368.30556172,  7051.68356244,
       11749.7369138 , 13921.41381955, 12282.45164472, 13265.12029092,
        9756.9998934 , 10555.05174087,  4690.22826757, 12072.50685247,
        8446.72203937])

In [14]:
r2_score(ytest, ypred)

0.8666204914540225

### Serialize the model coefficients using JSON

In [15]:
model.coef_

array([ 4.36524884e+01, -6.10785249e+01,  7.61964620e+02,  9.34976077e+01,
        5.01934211e+00,  1.23387934e+02, -4.09118708e+03, -4.74661863e+03,
       -6.53933051e+02, -4.64287530e+00,  1.79595157e+00, -1.46340629e+02,
        1.76822298e+02,  3.27598906e+03, -3.27598906e+03, -9.51367821e+02,
        9.51367821e+02, -2.90544910e+01,  2.90544910e+01,  2.29549467e+03,
       -1.25817425e+03, -3.50647698e+02,  3.75365169e+02, -1.06203789e+03,
       -1.17489047e+03, -1.63681304e+02,  1.33857178e+03, -5.01642848e+03,
        5.01642848e+03,  1.38304085e+02, -1.90662592e+03, -1.64995839e+03,
        2.87251101e+03,  2.11986758e+03, -5.01462751e+03,  3.44052915e+03,
        2.80180832e+03, -3.11619579e+03, -3.17227824e+03, -1.13272389e+03,
        6.86664437e+03, -5.68778392e+03,  3.44052915e+03,  8.36429021e+02,
        6.37722043e+02, -1.09526467e+03,  3.27598906e+03, -1.97816391e+03,
        4.42600422e+02, -2.11931197e+03,  0.00000000e+00])

In [16]:
model.intercept_

-31061.12699703782

In [ ]:
# JSON - JavaScript Object Notation

{
    "name":"Amit",
    
}

In [17]:
model_parameters = {}

model_parameters['coef'] = list(model.coef_)
model_parameters['intercept'] = model.intercept_.tolist()

In [19]:
# model_parameters

In [20]:
import json

In [21]:
json_text = json.dumps(model_parameters, indent=4)

json_text

'{\n    "coef": [\n        43.65248842316806,\n        -61.078524852259385,\n        761.9646198170216,\n        93.49760772223024,\n        5.019342110069658,\n        123.38793416388835,\n        -4091.1870813374258,\n        -4746.618629048639,\n        -653.9330511773751,\n        -4.642875300469768,\n        1.7959515723994173,\n        -146.34062930295931,\n        176.82229798527715,\n        3275.9890613903626,\n        -3275.9890613903463,\n        -951.3678206538059,\n        951.3678206538235,\n        -29.054490952728486,\n        29.054490952749944,\n        2295.4946670032573,\n        -1258.1742494610746,\n        -350.64769803584375,\n        375.36516905570136,\n        -1062.0378885620553,\n        -1174.8904709507092,\n        -163.68130432593617,\n        1338.5717752766443,\n        -5016.428481855389,\n        5016.428481855399,\n        138.30408451518477,\n        -1906.625924860555,\n        -1649.9583949249236,\n        2872.511011274352,\n        2119.8675838

In [23]:
# print(json_text)

#### save model parameters into a separate file

In [24]:
with open('models/regressor_parameters.txt', 'w') as file:
    file.write(json_text)

## Load the json model and generate predictions

In [25]:
with open('models/regressor_parameters.txt', 'r') as file:
    json_text_loaded = json.load(file)

In [28]:
# help(json.loads)

In [29]:
json_model = LinearRegression()

In [30]:
json_model.coef_ = np.array(json_text_loaded['coef'])
json_model.intercept_ = np.array(json_text_loaded['intercept'])

In [32]:
ypred_json = json_model.predict(xtest)

r2_score(ytest, ypred_json)

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


0.8666204914540225

the issue with json serialization is you need to know what model parameters should write to disk

If you go for more complex ml algo like, SVM, RandomForest than we have to go for pickle or joplib

## serializing ml model using pickle

In [33]:
import pickle

In [34]:
pickle.dump(model, open('models/pickle_model.pkl', 'wb'))  # write bytestream

In [35]:
# open the pickle model parameter and do the predictions

pickle_model = pickle.load(open('models/pickle_model.pkl', 'rb'))   # read bytestream

ypred_pickle = pickle_model.predict(xtest)

ypred_pickle

array([18619.15757811,  7662.62678786, 20822.50838869, 27539.25567201,
       17495.08927843, 11178.52046327,  6409.85832609, 14208.14141144,
       18674.54249815, 38283.29871344,  9005.03478484,  6949.49106947,
        7853.57661209, 16988.31650221,  9924.86067702,  9147.01488267,
        7246.29671961, 30082.33172101,  7854.61605152,  6273.90636822,
        5706.27220937, 21211.7248001 , 15423.67305019, 22017.09222772,
        9256.81830812,  8404.68250386,  7631.28471913,  8579.88251782,
        6409.85832609, 18782.0811832 ,  8368.30556172,  7051.68356244,
       11749.7369138 , 13921.41381955, 12282.45164472, 13265.12029092,
        9756.9998934 , 10555.05174087,  4690.22826757, 12072.50685247,
        8446.72203937])

In [36]:
pickle_r2_score = r2_score(ytest, ypred_pickle)

pickle_r2_score

0.8666204914540225

## serialize the ml model using joblib

- better for cases where the python objects hold huge numpy arrays

In [37]:
import joblib

In [38]:
filename = 'models/joblib_model.joblib'

joblib.dump(model, filename)      ## bytestream format

['models/joblib_model.joblib']

In [39]:
## open the model file and do the predictions

joblib_model = joblib.load(filename)

ypred_joblib = joblib_model.predict(xtest)

ypred_joblib

array([18619.15757811,  7662.62678786, 20822.50838869, 27539.25567201,
       17495.08927843, 11178.52046327,  6409.85832609, 14208.14141144,
       18674.54249815, 38283.29871344,  9005.03478484,  6949.49106947,
        7853.57661209, 16988.31650221,  9924.86067702,  9147.01488267,
        7246.29671961, 30082.33172101,  7854.61605152,  6273.90636822,
        5706.27220937, 21211.7248001 , 15423.67305019, 22017.09222772,
        9256.81830812,  8404.68250386,  7631.28471913,  8579.88251782,
        6409.85832609, 18782.0811832 ,  8368.30556172,  7051.68356244,
       11749.7369138 , 13921.41381955, 12282.45164472, 13265.12029092,
        9756.9998934 , 10555.05174087,  4690.22826757, 12072.50685247,
        8446.72203937])

In [40]:
joblib_r2_score = r2_score(ytest, ypred_joblib)

joblib_r2_score

0.8666204914540225

# resume training from checkpoint

In [41]:
xtrain.shape

(164, 51)

In [42]:
ytrain.shape

(164,)

In [43]:
ytrain.head()

133    12170.0
123     8921.0
157     7198.0
17     36880.0
76      5389.0
Name: price, dtype: float64

In [46]:
xtrain_part1 = xtrain[:85]

xtrain_part1.shape

(85, 51)

In [47]:
ytrain_part1 = ytrain[:85]

ytrain_part1.shape

(85,)

In [48]:
xtrain_part2 = xtrain[85:]

xtrain_part2.shape

(79, 51)

In [49]:
ytrain_part2 = ytrain[85:]

ytrain_part2.shape

(79,)

In [50]:
xtest.shape

(41, 51)

In [51]:
xtest_part1 = xtest[:20]
xtest_part1.shape

(20, 51)

In [52]:
xtest_part2 = xtest[20:]
xtest_part2.shape

(21, 51)

In [53]:
ytest.shape

(41,)

In [54]:
ytest_part1 = ytest[:20]
ytest_part1.shape

(20,)

In [55]:
ytest_part2 = ytest[20:]
ytest_part2.shape

(21,)

In [ ]:
## train the model on first part of the dataset

# xtrain_part1, ytrain_part1, xtest_part1, ytest_part1

In [57]:
xtrain_part1.head()

wheelbase  carlength  carwidth  carheight  curbweight  enginesize  \
133       99.1      186.6      66.5       56.1        2695         121   
123      103.3      174.6      64.6       59.8        2535         122   
157       95.7      166.3      64.4       52.8        2109          98   
17       110.0      197.0      70.9       56.3        3505         209   
76        93.7      157.3      64.4       50.8        1918          92   

     boreratio  stroke  compressionratio  horsepower  ...  \
133       3.54    3.07               9.3         110  ...   
123       3.35    3.46               8.5          88  ...   
157       3.19    3.03               9.0          70  ...   
17        3.62    3.39               8.0         182  ...   
76        2.97    3.23               9.4          68  ...   

     cylindernumber_twelve  cylindernumber_two  fuelsystem_1bbl  \
133                      0                   0                0   
123                      0                   0                0   
157                      0                   0                0   
17                       0                   0                0   
76                       0                   0                0   

     fuelsystem_2bbl  fuelsystem_4bbl  fuelsystem_idi  fuelsystem_mfi  \
133                0                0               0               0   
123                1                0               0               0   
157                1                0               0               0   
17                 0                0               0               0   
76                 1                0               0               0   

     fuelsystem_mpfi  fuelsystem_spdi  fuelsystem_spfi  
133                1                0                0  
123                0                0                0  
157                0                0                0  
17                 1                0                0  
76                 0                0                0  

[5 rows x 51 columns]

In [56]:
import sklearn

from sklearn.ensemble import RandomForestRegressor

In [58]:
scikitlearn_version = sklearn.__version__

scikitlearn_version

'1.0.2'

In [59]:
print(xtrain_part1.shape)
print(ytrain_part1.shape)

(85, 51)
(85,)


In [60]:
regressor_model = RandomForestRegressor(n_estimators=5, warm_start=True)

rfr_model = regressor_model.fit(xtrain_part1, ytrain_part1)

rfr_model

RandomForestRegressor(n_estimators=5, warm_start=True)

In [61]:
rfr_model.score(xtrain_part1, ytrain_part1)

0.9657442004501263

In [62]:
ypred_rfr_test = rfr_model.predict(xtest_part1)

rfr_test_score = r2_score(ytest_part1, ypred_rfr_test)

In [63]:
rfr_test_score

0.8737345483615351

In [64]:
# store the information for the resume traininig part

rfr_model_paramters = {}

rfr_model_paramters['model'] = rfr_model
rfr_model_paramters['sklearn_version'] = scikitlearn_version
rfr_model_paramters['r2_score'] = rfr_test_score

rfr_model_paramters

{'model': RandomForestRegressor(n_estimators=5, warm_start=True),
 'sklearn_version': '1.0.2',
 'r2_score': 0.8737345483615351}

In [65]:
# serialize the random forest regressor using joblib


import joblib


filename = 'models/rfr_model_checkpoint.joblib'

joblib.dump(rfr_model_paramters, filename)

['models/rfr_model_checkpoint.joblib']

In [66]:
# open the model and train it again on new data

joblib_model_new = joblib.load(filename)

In [67]:
joblib_model_new['model']

RandomForestRegressor(n_estimators=5, warm_start=True)

In [68]:
joblib_model_new['sklearn_version']

'1.0.2'

In [69]:
joblib_model_new['model'].n_estimators = 15

joblib_model_new['model']

RandomForestRegressor(n_estimators=15, warm_start=True)

In [71]:
xtrain_part2.shape

(79, 51)

In [72]:
rfr_retrained_model = joblib_model_new['model'].fit(xtrain_part2, ytrain_part2)

rfr_retrained_model.score(xtrain_part2, ytrain_part2)

0.9406774985074545

In [73]:
ypred_rfr_retrained_test = rfr_retrained_model.predict(xtest_part2)

rfr_retrained_test_score = r2_score(ytest_part2, ypred_rfr_retrained_test)

rfr_retrained_test_score

0.8152550979073039

In [74]:
# store the checkpoints again

retrained_rfr_model_paramters = {}

retrained_rfr_model_paramters['model'] = rfr_retrained_model
retrained_rfr_model_paramters['sklearn_version'] = scikitlearn_version
retrained_rfr_model_paramters['r2_score'] = rfr_retrained_test_score

retrained_rfr_model_paramters

{'model': RandomForestRegressor(n_estimators=15, warm_start=True),
 'sklearn_version': '1.0.2',
 'r2_score': 0.8152550979073039}

In [75]:
# save the model

filename = 'models/retrained_rfr_model_checkpoint.joblib'

joblib.dump(retrained_rfr_model_paramters,filename)

['models/retrained_rfr_model_checkpoint.joblib']