# Probability


In [ ]:
- Probability Distribution - likelihood of various outcomes
knowing the chances of different event occurings.

  Head       Tail
0 - 0.5    0.5 - 1

modeling uncertainty - 
parameter estimation - maximum likelihood estimation
generative models - Gaussian Mixture Models, Variational Autoencoders 
                  - use probability distributions to generate data samples
anomaly detection - 

fraud detection -> 
Sentiment analysis -> NLP - text data


In [ ]:
Conditional Probability

- measure of the likelihood of an event occuring, given that another event has already occured.

P(A|B)       =    P(A intersection B)  /  P(B)
conditional          joint probability    probability of event B occuring
probability


deck of cards -> 52

P(A) = 26/52 (card is red including hearts and dimonds)

P(B) = 12/52 (face cards including king, queen and jack)

P(A intersection B) = 6/52

conditional probability of getting a red card, given that it is a face card
P(A|B) = 6/52 / 12/52 = 6/12 = 1/2


- bayesian inference (statistical framework)
        - conditional probabilities are used to update the model parameters or hypothesis

- classification and decision tree (ensemble methods) - use condi.prob. to split data into subsets
- email spam - filter spam emails based on condi. prob.
- credit scoring - 
- autonomous vehicles - collision avoidance - likelihood of a collision given the current sensor data.



In [ ]:
Bayes Theorem
- how to update the probability for a hypothesis based on new data.

P(A|B) = P(B|A).P(A)/P(B)

P(A) - prior probability
P(B) - probability of data B

In [ ]:
find the probability of a patient having a disease(A)
given that a certain symptom(B)

P(A) = 0.01
P(B|A) = 0.9
P(B|-A) = 0.2

P(A|B)  = P(B|A).P(A)/P(B|A).P(A) + P(B|-A).P(-A)

P(A|B) = 0.0435 => 4.35%

# Naive Bayes

In [ ]:
P(A|B,C,D,E)

P(A|'free', 'discount', 'money')

- text classification - spam email detection, sentiment analysis, document categorization
- multiclass classification
- user review analysis

In [ ]:
Gaussian NB - continuous data, features are normally distributed
Multinomial NB - discrete data, counts or frequencies
Bernoulli NB - binary or discrete data, assumes Bernolli distribution

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
# iris

In [4]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
from sklearn.naive_bayes import GaussianNB

gb = GaussianNB()

gb.fit(df, iris.target)

GaussianNB()

In [6]:
gb.score(df, iris.target)


0.96

In [7]:
gb.predict([[5.1,3.5,1.4,0.2]])

C:\Users\himan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0])

In [8]:
docs = pd.read_table('SMSSpamCollection+(1)', header=None, names=['Class', 'SMS'])

docs.head()

Class                                                SMS
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
ham_spam = docs.Class.value_counts()

ham_spam

ham     4825
spam     747
Name: Class, dtype: int64

In [10]:
docs['label'] = docs.Class.map({ 'ham':0, 'spam':1 })

docs.head()

Class                                                SMS  label
0   ham  Go until jurong point, crazy.. Available only ...      0
1   ham                      Ok lar... Joking wif u oni...      0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...      1
3   ham  U dun say so early hor... U c already then say...      0
4   ham  Nah I don't think he goes to usf, he lives aro...      0

In [11]:
x = docs.SMS
y = docs.label

print(x.shape)
print(y.shape)

(5572,)
(5572,)


In [12]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x,y, random_state=101)

In [13]:
xtrain.head()

1851    Then cant get da laptop? My matric card wif ü ...
3280    Solve d Case : A Man Was Found Murdered On  &l...
3426                      True. Its easier with her here.
111              What is the plural of the noun research?
3788                          WHORE YOU ARE UNBELIEVABLE.
Name: SMS, dtype: object

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(stop_words='english')

vect.fit(xtrain)

CountVectorizer(stop_words='english')

In [16]:
# vect.vocabulary_

In [17]:
xtrain_transformed = vect.transform(xtrain)
xtest_transformed = vect.transform(xtest)

In [18]:
from sklearn.naive_bayes import MultinomialNB

mnb = MultinomialNB()

mnb.fit(xtrain_transformed, ytrain)

ypred_class = mnb.predict(xtest_transformed)

ypred_proba = mnb.predict_proba(xtest_transformed)

In [19]:
from sklearn.metrics import accuracy_score

accuracy_score(ytest, ypred_class)

0.9849246231155779

In [20]:
ypred_class

array([0, 1, 1, ..., 0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import confusion_matrix

confusion_matrix(ytest, ypred_class)

array([[1219,    8],
       [  13,  153]], dtype=int64)