# Vectors

### 1 - Dot product

- similarity calculations 

-> text analysis

-> search engines -> semantic seaerch (search on the basis of context rather than keyword only)

-> palgiarism detectors

In [1]:
import numpy as np

v = np.array([1,2,3])
u = np.array([4,5,6])

print(np.dot(v,u))

32


## 2 - Vector Addition

- aggregation

-> sentiment analysis - individual sentiment score(vectors) and can add to determine the overall sentiment of the text
"your t-shirt is looking killer"



In [ ]:
# ASCII

A -> 65/2 -> binary 
B -> 66
Z -> 90

In [3]:
w = v + u
print(w)

[5 7 9]


## 3 - Element wise multiplication(Hadamard Product)

- Optimization - stock portfolio - investment strategy

-> performance of a portfolio

v -> asset return

u -> weights



In [4]:
w = v * u

print(w)

[ 4 10 18]


## 4 - Vector Norm(L2 Norm)

- image quality

- l2 normalization is difference between reference and distorted vectors

- medical imaging, content delivery platforms

In [5]:
l2 = np.linalg.norm(v)

print(l2)

3.7416573867739413


## 5 - Transposition

- customer segmentation - preferences or behaviours

- flipping an image

In [6]:
print(v.T)

[1 2 3]


## 6 - Vector concatenation

- user profile enrichment -> personalized the experience

In [8]:
w = np.concatenate((v,u))

print(w)

[1 2 3 4 5 6]


## 7 - Cross product

- 3D graphics and simulation

- it is used in physics simulations to calculate normal vectors

- rendering realistic 3D scenes

In [9]:
w = np.cross(v,u)

print(w)

[-3  6 -3]


# Matrix

## 1 - Matrix Multiplication(dot product)

- image processing

- CNN - Convolutional Neural Network - feature map(image matix * filter matrix)

- to extract features from an image

In [10]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.dot(matrix1, matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


## 2 - Matrix Inversion

- find the optimal coefficient for the regression model

- minimizing the sum of squared errors

In [ ]:
y = mx + c

y = m1x1 + m2x2 + m3x3 + c + e

In [11]:
print(np.linalg.inv(matrix1))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


## 3 - Singular Value Decomposition(SVD)

- recommendation systems

- matrix factorization -> factors in user-item interaction - improve quality of our recommendation

- how the inverse helping in the recommnedation quality

In [12]:
print(np.linalg.svd(matrix1))

(array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), array([1.68481034e+01, 1.06836951e+00, 1.40266540e-16]), array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [ 0.40824829, -0.81649658,  0.40824829]]))


## 4 - Addition of Matrix

- nlp - combine word embeddings to represent sentences or docs as vectors

In [13]:
print(matrix1 + matrix2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## 5 - Covariance Matrix

- EDA - relationship between diffrent features

In [14]:
print(np.cov(matrix1))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 6 - Determinent

- use this to check if there is multicollinearity between features in regression model

In [15]:
print(np.linalg.det(matrix1))

-9.51619735392994e-16


# 7 - Rank

- help us indentify- linearly dependent features

In [16]:
print(np.linalg.matrix_rank(matrix1))

2


# Interview Questions

In [ ]:
# 1. Whats the difference between vectors and matrix?

# - vectors - 1-d array - represent a point or a quantity with both magnitude and direction

# - matrix - 2-d array - represents a collection of data.

In [ ]:
# 2 - What is the importance of matrix multiplication in ML?

# - linear transformations, feature transformation, updating a parameter in neural networks

# modeling relationship in data

In [ ]:
# 3 - Concept of transposition

# switching rows and columns wrt pricipal diagonal
# flipping an image
# customer segmentation

In [ ]:
# 4 - What is a determinent

# reperents a scaling factor
# check multicollineaerity in the data

In [ ]:
# 5 - how matrix factorization is used in recommendation system.

# user-item interation 
# to predict user preferences and suggest items better